# Copyright (c) 2015-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD+Patents license found in the
# LICENSE file in the root directory of this source tree.

-include makefile.inc

SRC=$(wildcard *.cpp)
OBJ=$(SRC:.cpp=.o)
JAVAWRAP=$(SRC:.cpp=_wrap.cpp)

############################
# Building

default: libfaiss.a

all: libfaiss.a libfaiss.$(SHAREDEXT)

java: $(OBJ)
	[ -d java ] || mkdir java
	[ -d java/class ] || mkdir java/class
	$(SWIG) -c++ -java -package com.facebook.research.faiss -outdir java -o faiss_swig_wrap.cpp swig/faiss.i
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(CPUFLAGS) -I. -I$$JAVA_HOME/include \
		-I$$JAVA_HOME/include/linux -c faiss_swig_wrap.cpp 
	$(CXX) $(SHAREDFLAGS) $(LDFLAGS) *.o -o libfaiss_swig.so $(LIBS)
	$(JAVAC) -target $(JAVA_TARGET) -d java/class/ java/*.java
	cd java/class && \
	$(JAR) -cf ../../faiss.jar com

libfaiss.a: $(OBJ)
	ar r $@ $^

libfaiss.$(SHAREDEXT): $(OBJ)
	$(CXX) $(SHAREDFLAGS) $(LDFLAGS) -o $@ $^ $(LIBS)

%.o: %.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(CPUFLAGS) -c $< -o $@

clean:
	rm -rf java/ faiss_swig_wrap.cpp
	rm -f libfaiss.*
	rm -f $(OBJ)

clean_java:
	rm -rf java/ faiss_swig_wrap.cpp faiss.jar libfaiss_swig.so

############################
# Installing

install: libfaiss.a libfaiss.$(SHAREDEXT) installdirs
	cp libfaiss.a libfaiss.$(SHAREDEXT) $(DESTDIR)$(libdir)
	cp *.h $(DESTDIR)$(includedir)/faiss/

installdirs:
	$(MKDIR_P) $(DESTDIR)$(libdir) $(DESTDIR)$(includedir)/faiss

uninstall:
	rm $(DESTDIR)$(libdir)/libfaiss.a
	rm $(DESTDIR)$(libdir)/libfaiss.$(SHAREDEXT)
	rm -rf $(DESTDIR)$(includedir)/faiss


#############################
# Dependencies

-include depend

# The above makefile.dep is generated by the following target:
depend:
	for i in $(SRC); do \
		$(CXXCPP) $(CPPFLAGS) -MM $$i; \
	done > depend


#############################
# Tests

test: libfaiss.a py
	make -C tests run
	PYTHONPATH=./python/build/`ls python/build | grep lib` \
	$(PYTHON) -m unittest discover tests/ -v


#############################
# Demos

demos: libfaiss.a
	make -C demos


#############################
# Misc

misc/test_blas: misc/test_blas.cpp
	$(CXX) $(CXXFLAG) $(LDFLAGS) -o $@ $^ $(LIBS)


#############################
# Python

py:
	$(MAKE) -C python build


.PHONY: all java clean clean_java default demos install installdirs py test uninstall
